services:
  - type: web
    name: portfolio-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_site.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: Dishant's Portfolio.onrender.com
